### ISSUE TITLE
Curl not found

### ISSUE THREAD

**Issue by mikyjazz** [resoai/TileBoard-addon#1]
Hi, I get this error (curl not found) at startup...
On Raspberry pi4 with raspbian 32 bit
Homeassistant Version core-2021.2.3
Hassio Version supervisor-2021.02.6

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
/usr/lib/bashio/api.sh: line 47: curl: command not found
[00:18:08] ERROR: Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] tile-board.sh: executing... 
[00:18:10] INFO: Symlink files to dist folder
[cont-init.d] tile-board.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:18:10] INFO: Starting NGinx server...

**Comment by mikyjazz** [comment]
I see you fixed this

**Comment by rchl** [comment]
Yes, I believe I did now.

Note that probably, due to this error, the addon would not update itself or even report there is a new version available so it has to be manually removed and re-added.

Also, note that I haven't really decided to announce this addon publicly yet as I have some potentially breaking changes planned. Just don't have time to work on that.

**Comment by mikyjazz** [comment]
Hi Rafal,
thanks for your kind reply.
I accidentally discovered Tileboard looking for something that would allow me to arrange the dashboard in an orderly and not random way (as lovelace does by default).
Now I'll try to configure something to see what I can achieve.
I would like to ask you if with this docker installation the security problem with respect to unauthenticated access from the outside has been solved; actually it's not a big problem because I saw that it is possible to leave both interfaces - in this way I would use TIleboard only on the internal network, also because I only use the mobile app from the external network.
Time is a problem, I too have started to develop a component for scheduling heating and thermostatic valves but I never find the time to finish ...
I thank you for your work and I salute you.
I will follow all the updates and let you know if there are any news.
Greetings
Michele

**Comment by rchl** [comment]
> I would like to ask you if with this docker installation the security problem with respect to unauthenticated access from the outside has been solved; actually it's not a big problem because I saw that it is possible to leave both interfaces - in this way I would use TIleboard only on the internal network

I guess you are referring to this warning from the TileBoard readme: https://github.com/resoai/TileBoard#warning ?

The way this add-on works is more secure than running TileBoard from `/local/tileboard` because it runs on a separate port from the HA interface itself so you can only expose the HA port but not TileBoard one to the Internet and nobody will be able to access TileBoard from the outside.

But if you expose this addon's port to the Internet then the same rules apply as with plain TileBoard - people will be able to access all TileBoard source files, including your configuration file but they won't be able to log in so they won't be able to control anything or see any entities.

**Comment by mikyjazz** [comment]
Yes, that was what I meant.
All right, as I said, it will be enough not to open the Tileboard door to the outside.
Thanks again
See you soon
